### ISSUE TITLE
og image是舊的忍者圖

### ISSUE THREAD

**Issue by deeper747** [Disfactory/about.disfactory.tw#15]
**The problem**
分享時，現在facebook的OG image跑不出來，twitter則是抓到舊的圖片

<img width="503" alt="截圖 2021-02-09 上午8 04 14" src="https://user-images.githubusercontent.com/60970217/107296984-69180380-6aad-11eb-938b-818a082fcafb.png">

<img width="594" alt="截圖 2021-02-09 上午8 02 02" src="https://user-images.githubusercontent.com/60970217/107296830-1d655a00-6aad-11eb-902f-6aa45d7bec79.png">

Device: Macbook Pro
OS: MacOS Catalina
Browser: Chrome 版本 88.0.4324.150

**Comment by deeper747** [comment]
device: i7
os: iOS 14.4
browser: safari

在facebook上分享有鄉鎮市區的網址：顯示了bad gateway
![IMG_0632](https://user-images.githubusercontent.com/60970217/107298899-3ff97200-6ab1-11eb-9494-075a0ad192fd.PNG)

分享單純about.disfactory.tw的網址：顯示了全國數字的OG圖
![IMG_0633](https://user-images.githubusercontent.com/60970217/107298908-44be2600-6ab1-11eb-9da3-2a163aa3860f.PNG)

**Comment by yeefun** [comment]
這個 commit eee438bbd6fe781fbee89997c2fe27be264a5792 解決了，如果圖片依然是錯的，可用[這個工具](https://developers.facebook.com/tools/debug/)來重新抓取 meta 內容。
