### ISSUE TITLE
員林市的統計

### ISSUE THREAD

**Issue by deeper747** [Disfactory/about.disfactory.tw#16]
「員林市」統計是0，但好像是因為在about這邊被寫成「員林鎮」了

<img width="1428" alt="截圖 2021-02-09 上午10 43 46" src="https://user-images.githubusercontent.com/60970217/107308493-b2734d80-6ac3-11eb-8005-55c4e5127ba6.png">
<img width="1078" alt="截圖 2021-02-09 上午10 43 32" src="https://user-images.githubusercontent.com/60970217/107308528-c28b2d00-6ac3-11eb-81f2-30b6e7690607.png">

**Comment by yeefun** [comment]
原來有升格過⋯⋯

> 2015年8月8日，「員林鎮」因立法院通過《地方制度法部分條文修正案》（15萬降為10萬）而受惠，如願升格為「員林市」]。
