### ISSUE TITLE
Add contributor list

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/about.disfactory.tw#50]
I want to add a section to thank the contributors.

For example,
https://vaxx.tw/credits

It can be a link to a HackMD or plain html without design, or one section embedded in the about page.

**Comment by aelcenganda** [comment]
contributor list 新增在 g0v logo 和聯繫地球公民基金會中間。

@aelcenganda 會給名單

目前還沒有設計稿，最差就是用以下的 layout

![螢幕快照 2021-09-29 下午8 22 44](https://user-images.githubusercontent.com/9480974/135267609-badf70cc-23fd-4af5-8524-bc9296a5cdeb.png)

**Comment by deeper747** [comment]
我最近一次簡報寫的，再加上典洋XD：

前端：IU、yukai、yeefun、david
設計：SL、J、Xinroo、RAY、tin、Lydia
後端：cph、yellowsoar、swind、小白、Jsaon、Toby、Sonia、Andy、Darren、Looofy、Simon、Aaron、Hubert
PM：ael
地球公民基金會：小海、deeper、小胖、沅諭、可飛、peii
社群協力：shupo、Joycelin、ronnywang、pm5、kiang、ddio、laiTzan、chelin、jenhaoyang、chihao、Amgel、安東尼、Bryce、笑笑、積丹尼、誠夏、chewei、昱伶、chiahe、yenchia、Lydia、Stasia、慈忻

**Comment by aelcenganda** [comment]
前端：IU、yukai、yeefun、dotsea、Caleb
設計：SL、J、tin、Lydia、Xinroo、RAY
後端：cph、yellowsoar、swind、小白、Yen-Chia、sour、Jsaon、Toby、Sonia、Andy、Hubert、Darren、Looofy、Simon、Aaron
圖資/GIS: chewei、ronnywang、bdon、pm5、kiang、shupo
PM：ael
地球公民基金會：小海、deeper、小胖、沅諭、可飛、peii
社群協力：ddio、chiahe、Joycelin、laiTzan、chelin、jenhaoyang、chihao、Angel、安東尼、Bryce、笑笑、積丹尼、誠夏、昱伶、Stasia、慈忻、Kai、昱玲、Tai、Wuulong、Carmen、fly、土撥鼠、mhshih、JinWen、Johnson、John Huang

**Comment by deeper747** [comment]
昱玲的伶應該是人令伶，剛剛跟小海確認過

**Comment by wutingy** [comment]
前端：IU、yukai、yeefun、dotsea、Caleb
設計：SL、J、Tin、Lydia、Xinroo、RAY
後端：cph、yellowsoar、swind、小白、Yen-Chia、sour、Jsaon、Toby、Sonia、Andy、Hubert、Darren、Looofy、Simon、Aaron
圖資/GIS: chewei、ronnywang、bdon、pm5、kiang、shupo
PM：ael
地球公民基金會：小海、deeper、小胖、沅諭、可飛、peii
社群協力：ddio、chiahe、Joycelin、laiTzan、chelin、jenhaoyang、chihao、Angel、安東尼、Bryce、笑笑、積丹尼、誠夏、昱伶、Stasia、慈忻、Kai、昱伶、Tai、Wuulong、Carmen、fly、土撥鼠、mhshih、JinWen、Johnson、John Huang

**Comment by fhjqwefa** [comment]
[Contributor_Phase1_Mobile_Static](https://www.figma.com/file/vnvt7JjXrRcXZlqLoW2vCZ/About.Disfactory?node-id=469%3A900)
[Contributor_Phase1_Mobile_Prototype](https://www.figma.com/proto/vnvt7JjXrRcXZlqLoW2vCZ/About.Disfactory?node-id=462%3A499&scaling=scale-down&page-id=0%3A1&starting-point-node-id=455%3A218)

**Comment by fhjqwefa** [comment]
[貢獻者名單改由footer文字進入](https://www.figma.com/file/vnvt7JjXrRcXZlqLoW2vCZ/About.Disfactory?node-id=1%3A191)

**Comment by dyfu95** [comment]
@aelcenganda @deeper747 社群協力裡有兩個「昱伶」，是剛好有兩個同名的貢獻者，還是誤植？

**Comment by aelcenganda** [comment]
應該是誤植

**Comment by dyfu95** [comment]
10/31 修正項目：

- 修正名單：刪除社群協力中重複出現的「昱伶」。
- 解決破版問題：部署後，發現文字內容會超出邊界而不會自動換行。後來發現是css設定錯誤，已調整為自動換行。

上述問題已修正並更新網頁。

**Comment by aelcenganda** [comment]
貢獻者名單可以從 code 直接改
https://github.com/Disfactory/about.disfactory.tw/edit/dev/components/TheFooter.vue#L104-L107

**Comment by peii052** [comment]
新增貢獻者名單
前端：二路、KuoMin
設計：ryno
後端：steven、ifengc、kai wang、tuo
圖資：karen
社群協力：sarah
