### ISSUE TITLE
petition campaign

### ISSUE THREAD

**Issue by deeper747** [Disfactory/about.disfactory.tw#61]
地球公民將在2022年1月開始推一個為期約100天的連署，希望在about頁面上加一個連署的section或是button

連署頁面：https://www.cet-taiwan.org/farm/act4

**Comment by deeper747** [comment]
設計圖：https://www.figma.com/file/vnvt7JjXrRcXZlqLoW2vCZ/About.Disfactory

**Comment by Oriyar** [comment]
我覺得可以加一個按鈕寫「連署消滅它」，放在「分享」「在哪里？」的旁邊。

我想像的情境是來到about的人，無論是否有搜尋家鄉，看到54,807+工廠後，願意點擊「連署消滅它」的應該就是希望違章工廠消失。因此進入連署頁面後看到標題：連署要求經濟部終結農地工廠，這樣的資訊就夠了。（不用懂工輔法或什麼斷水斷電之類，總之想消滅它，連署就對了！）

**Comment by deeper747** [comment]
網址請放這個！ https://bit.ly/3FShGWe

**Comment by dyfu95** [comment]
done by commit  0061718b65a26927703dc9b74d2883d1501ad064
