### ISSUE TITLE
「OO縣/市民眾要加油囉！👊」要顯示的是最後一名

### ISSUE THREAD

**Issue by deeper747** [Disfactory/about.disfactory.tw#66]
現在在各縣市回報進度底下「OO縣/市民眾要加油囉！👊」顯示了第一名的嘉義市
但應該要是最後一名的「雲林縣」才對

**Comment by dyfu95** [comment]
done by commit 59d56a52dfa7519a9bb6e5b03a6efcb9f2522c28
