### ISSUE TITLE
「分享」到臉書時帶入文字

### ISSUE THREAD

**Issue by deeper747** [Disfactory/about.disfactory.tw#67]
現在按「分享」時，所有途徑都會帶入下列文字：

> 🧧我肚子裡的年菜有被工廠加料嗎？🧧
> 
> #農地違章工廠 #即報即拆 #拒絕污染 #加入回報 #disfactory https://about.disfactory.tw/
> 

但facebook的現在只剩下「#農地違章工廠」

https://user-images.githubusercontent.com/60970217/150460992-9290a974-0927-4a51-9d0c-6b0be9131f34.MP4

希望可以加回上面有紅包emoji那個文案

**Comment by dyfu95** [comment]
剛查了一下，應該是facebook禁止在分享的文字中，由網站預先填入內容。
更精確地說，facebook允許預先填入一個主題標籤(hashtag)，所以會造成目前僅有 **#農地違章工廠** 這個hashtag。

https://developers.facebook.com/docs/development/terms-and-policies/prefill-policy-deep-dive/

**Comment by aelcenganda** [comment]
補個脈絡，是因為 2020 年  8 月政策改變

The new Facebook Platform Terms and the new Developer Policies below went into effect on August 31, 2020. They replace the legacy Facebook Platform Policy and the legacy Instagram Platform Policy, as well as the Supplemental Terms for Extended Platform Products and the Technology Provider Amendment to the preceding Supplemental Terms. Learn more.

**Comment by aelcenganda** [comment]
@deeper747 就看你 hashtag 要放什麼了

**Comment by deeper747** [comment]
希望可以變成

> #我肚子裡的年菜有被違章工廠加料嗎

**Comment by dyfu95** [comment]
@deeper747 是要
1. 新增一個hashtag，變成

> 🧧我肚子裡的年菜有被工廠加料嗎？🧧
> #我肚子裡的年菜有被違章工廠加料嗎 #農地違章工廠 #即報即拆 #拒絕污染 #加入回報 #disfactory https://about.disfactory.tw/

還是
2. 將紅包emoji那個文案變成hashtag

> #我肚子裡的年菜有被工廠加料嗎
> #農地違章工廠 #即報即拆 #拒絕污染 #加入回報 #disfactory https://about.disfactory.tw/

如果是要2.的話，hashtag後面不能加emoji。如果加了，臉書會吃不到那個hashtag的文字

**Comment by deeper747** [comment]
噢噢我當時留的時候是回應「facebook現在只能放一個『hashtag』」這件事，所以才想說那個hashtag就留最重要的一句話

但沒有思考到現在全部的分享是不是都是**共用同一份字串**
如果是**共用同一份字串**的話，那就是1沒錯（理論上這樣facebook抓的時候，就會只留第一個hashtag對不？

**Comment by dyfu95** [comment]
>（理論上這樣facebook抓的時候，就會只留第一個hashtag對不？

對，不管你留幾個hashtag，facebook就是只准我們填入第一個hashtag而已。
剛自己測試後，hastag有幾個特性：
1. 加入全形空白、半形空白、全形標點符號、半形標點符號會被視為斷點。
如果你留以下情形，都只會出現 **#前方文字**
> #前方文字 後方文字
> #前方文字　後方文字
> #前方文字?後方文字
> #前方文字？後方文字

2.不含#本身，一個hashtag可以寫最多32個中文字。英文不確定，但如果以1中文=2字元數計算，可以寫到最多64個英文字母？

**Comment by deeper747** [comment]
🧧我肚子裡的年菜有被工廠加料嗎？🧧
#我肚子裡的年菜有被違章工廠加料嗎 #農地違章工廠 #即報即拆 #拒絕污染 #加入回報 #disfactory https://about.disfactory.tw/

J個

**Comment by dyfu95** [comment]
done by commit  4281404cbeffaa5e35d247c15227a2b5d3664ee4
